<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_The Gold Chain GCH00140001 Ships Faster</name>
   <tag></tag>
   <elementGuidId>127b71a7-356c-4df8-9a73-9fff874b25bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='prodListingUl']/li[6]/div/div[2]/div/div/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c27e72b4-7006-4333-934e-0473c6c23e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/the-gold-chain-gch00140001-ships-faster.html?bid=MTkyMg==</value>
      <webElementGuid>fce7fdfc-5157-4ff9-95cf-1262272d4777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8af776c1-0e84-4244-8987-d5c7105307a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Gold Chain GCH00140001 Ships Faster</value>
      <webElementGuid>d5baefaa-1860-4723-a33d-619781345944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prodListingUl&quot;)/li[@class=&quot;col-xs-6  col-lg-3 pdt-item-list&quot;]/div[@class=&quot;bx-contr&quot;]/div[@class=&quot;deatils pos-rel&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 title-section text-center ss&quot;]/div[@class=&quot;hidden-xs&quot;]/h2[@class=&quot;productTitle h5style font-medium rmv-padding text-overflow margin-bottom&quot;]/a[1]</value>
      <webElementGuid>6c120078-1e81-43b3-aa3e-e06bba5708a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='prodListingUl']/li[6]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>b62df3c7-a0e1-495b-a370-a2abf62c2a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'The Gold Chain GCH00140001 Ships Faster')]</value>
      <webElementGuid>881d8b1c-687b-4da8-8dfb-704014ca73e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW DETAILS'])[11]/following::a[2]</value>
      <webElementGuid>3ec8d454-3209-4832-8f1f-f98b3d474865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUY NOW'])[11]/following::a[3]</value>
      <webElementGuid>4ff00ed5-652a-4b9b-b599-01cb14acd2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹57,191'])[1]/preceding::a[1]</value>
      <webElementGuid>a28e836f-efab-4589-bf2a-d5418477556d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold Chain'])[7]/preceding::a[1]</value>
      <webElementGuid>4363ba0b-927e-403f-b26e-ac99d3e3de01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Gold Chain GCH00140001 Ships Faster']/parent::*</value>
      <webElementGuid>59b03c0e-0d6b-4875-9ac2-2ac38a28de38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/the-gold-chain-gch00140001-ships-faster.html?bid=MTkyMg==')])[2]</value>
      <webElementGuid>2ed5b847-87ca-4b3a-9626-907a71b102f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>af4625d2-dd0e-4542-83eb-c12387af9d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/the-gold-chain-gch00140001-ships-faster.html?bid=MTkyMg==' and (text() = 'The Gold Chain GCH00140001 Ships Faster' or . = 'The Gold Chain GCH00140001 Ships Faster')]</value>
      <webElementGuid>55879e5f-3e51-4730-9526-7d728de28436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
