<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_userLoginEmail</name>
   <tag></tag>
   <elementGuidId>a0cd2a84-36d1-4847-a92d-ff9cc9f0b190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userLoginEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userLoginEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>177a28f3-82de-430c-abd2-8bdb904f8bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b784eb0-e221-4ed6-a0cc-7fa26c862086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userLoginEmail</value>
      <webElementGuid>1fffe0ae-59de-4831-bc1d-4c73b6f25717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input</value>
      <webElementGuid>7bf9a891-17e4-41ef-b27c-752b053d49d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5d1f3cef-13f7-45ef-adf9-8851f4dbef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4c75131-d45a-408b-93c1-1e6acbaea9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userLoginEmail</value>
      <webElementGuid>1c3b0e37-5233-4070-ba2d-2b447cf781ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userLoginEmail&quot;)</value>
      <webElementGuid>0b13075e-bbd4-4a28-8863-8eec31b458be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PCJ/Login/iframe_Loading_loginPopup</value>
      <webElementGuid>390ad7f3-7310-4484-90cd-3d2511dbe09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userLoginEmail']</value>
      <webElementGuid>7c050142-6306-458a-a52f-d4326a4c92b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div/fieldset/ul/li/input</value>
      <webElementGuid>932f7e0d-b6f8-4e8b-8896-2cd17e9a2f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>ce3ad37a-de3e-4f4d-9a63-9ca64c84e7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userLoginEmail' and @id = 'userLoginEmail']</value>
      <webElementGuid>7e32316f-7a7e-41cc-81cc-5fe55d70dcc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
