<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_userLoginPassword</name>
   <tag></tag>
   <elementGuidId>5c07c7a8-778d-4630-97a3-c1ddfe8780c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userLoginPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userLoginPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e40243c5-be37-487c-b9f4-96bf954411ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e33b648d-64ee-4d43-908f-2877ed0d95ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userLoginPassword</value>
      <webElementGuid>d0e3e3b2-3949-48cf-a42a-71f8bd50f69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input</value>
      <webElementGuid>db8e014a-683d-4852-a92f-5fe88821f2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>51d9dc30-c9a6-4190-ad69-5f624a7d6b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ec4ef6e-4558-4617-825a-af74df21486d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userLoginPassword</value>
      <webElementGuid>74f4f0e1-167d-42d8-bf19-be5e33544a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userLoginPassword&quot;)</value>
      <webElementGuid>29f6c301-7cfb-4179-9fb7-6f7655897740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PCJ/Login/iframe_Loading_loginPopup</value>
      <webElementGuid>d99769c2-2150-409a-abcd-0564ce5b4395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userLoginPassword']</value>
      <webElementGuid>ed3ab6c7-44e0-4a28-bbae-25f0abd1c35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div/fieldset/ul/li[2]/input</value>
      <webElementGuid>3c0c8829-708a-4c71-af48-78de4903d808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>6277adc7-1d22-4d6d-8ae6-b91e66b826ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'userLoginPassword' and @id = 'userLoginPassword']</value>
      <webElementGuid>f24b2018-ccdd-4c6c-9a83-f73b203df9a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
