<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_12</name>
   <tag></tag>
   <elementGuidId>a100a050-cb59-4700-8256-8983f9913469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opt_1070_165243']/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>681c1527-1c38-4752-82ed-25a229d67c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1584884</value>
      <webElementGuid>fe5635b2-0b96-42c0-a4bb-f647983e3d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c5b6904f-a94e-469c-8e7f-6397a56d45db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ae203ac1-8bb7-4b44-a3b9-9557ca39009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt_1070_165243&quot;)/div[@class=&quot;nice-select listbox pull-left form-control custom_option inv_no variantAddtoCart open&quot;]/ul[@class=&quot;list&quot;]/li[@class=&quot;option&quot;]</value>
      <webElementGuid>423876bb-314d-4575-8902-a8a7b335cc8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opt_1070_165243']/div/ul/li[3]</value>
      <webElementGuid>9f907475-bd34-43c6-8fa9-b6ca48f98536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{11'])[2]/following::li[1]</value>
      <webElementGuid>326715e0-d8bf-4243-807b-8db324b68049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Size'])[3]/following::li[2]</value>
      <webElementGuid>fc925063-7079-46c5-b83e-05f7f62c8a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select Size'])[1]/preceding::li[12]</value>
      <webElementGuid>b3a7ebf5-5d22-4104-870b-4ed7d28cd48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size chart'])[1]/preceding::li[12]</value>
      <webElementGuid>b0f36839-f789-45fa-b0f7-da8764210972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/ul/li[3]</value>
      <webElementGuid>da07351d-91d1-4a6f-9c05-468b2e4cc404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '12' or . = '12')]</value>
      <webElementGuid>78836bdf-6dac-4b1a-9d91-c2cf67ae2723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
