<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_18KT</name>
   <tag></tag>
   <elementGuidId>18f54e75-9a43-4b6f-9944-5238376023b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='variant_thumb_image_342667']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#variant_thumb_image_342667</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91fe216a-5335-44e4-9476-4bfed002ce0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-imag-list  object-image hand</value>
      <webElementGuid>8f9d2e33-be28-40a9-adb2-1ee69d8c1353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>variant_thumb_image_342667</value>
      <webElementGuid>f350795a-d893-4c3c-9584-5d23852514de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; fn_set_options(this,'1070', '168318','342667');</value>
      <webElementGuid>b0d39171-4086-4893-a82f-464521394dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 18KT</value>
      <webElementGuid>53af1389-e8f1-422e-af9c-581a87ff3cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;variant_thumb_image_342667&quot;)</value>
      <webElementGuid>bac03b00-c648-42f3-86cc-4e9f38125c59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='variant_thumb_image_342667']</value>
      <webElementGuid>9aaea68c-1562-49d3-8702-63e51f97023a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_2_container']/div/span[2]</value>
      <webElementGuid>3f4d00a9-4140-4103-aa2e-914c9e02b32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yellow Gold'])[2]/following::span[2]</value>
      <webElementGuid>b347561e-c7b0-4b5a-a4c3-c53caecc10c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='White Gold'])[3]/following::span[2]</value>
      <webElementGuid>9404b62c-c434-491e-a2cb-56dbdf31d5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stone'])[1]/preceding::span[2]</value>
      <webElementGuid>a23b196e-3efd-40db-b2af-172dfd32e435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IJ-SI'])[1]/preceding::span[3]</value>
      <webElementGuid>1f935998-f8c0-41aa-9c72-7024ec5fc6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='18KT']/parent::*</value>
      <webElementGuid>44c477f7-1f16-4b61-9bfc-4e5b958b5031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/span[2]</value>
      <webElementGuid>34d2b8dc-f6fa-4a00-b9a2-0973980dbd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'variant_thumb_image_342667' and (text() = ' 18KT' or . = ' 18KT')]</value>
      <webElementGuid>ce40c7f2-730e-4ffe-9047-4aaedffbb13e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
