<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Loading_loginPopup</name>
   <tag></tag>
   <elementGuidId>79cc726d-06cc-48f2-b441-84efa74ce49b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframeLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>19e9c89c-59ad-4232-881a-9be34ab199a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeLogin</value>
      <webElementGuid>e6ce2e6f-42d7-4fa8-b63f-7fe797e45411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginPopup</value>
      <webElementGuid>65122a15-68d1-4c20-8a31-10f0ffe33467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=user/wishlist/productid/42610</value>
      <webElementGuid>b703985f-5b0a-4fae-99f9-61b6e4c44285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickpopup</value>
      <webElementGuid>580b0216-94c4-4763-b1c0-fba52204317d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df8dd10c-aa0b-4682-8b62-a0026e4f4ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b17c7633-7e4b-4821-88b3-887fdc2178bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f67a8216-5caf-4db6-9b80-03c54ff01138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e989b988-a259-4daa-a96f-933527f350e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>20203549-605a-4f45-bc1a-dae21c24e9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeLogin&quot;)</value>
      <webElementGuid>2a477faa-5c23-48b9-ad85-69deb6cb61f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeLogin']</value>
      <webElementGuid>c5a5cd9d-4b21-431b-82c5-18db32c42ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/div/iframe</value>
      <webElementGuid>e6724f5a-b27e-4d36-b5ba-66f626a16da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Gifting'])[1]/preceding::iframe[1]</value>
      <webElementGuid>6047e4a7-0947-4cd8-a0a9-41e1dc1e38ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b0e965db-04e8-4edc-84d3-3b9e829f87c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeLogin' and @name = 'loginPopup' and @src = 'https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=user/wishlist/productid/42610']</value>
      <webElementGuid>03e3bcc9-9044-4f6f-9908-36353959bcd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
