<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Print</name>
   <tag></tag>
   <elementGuidId>4ae45fca-63e7-4e58-ab6c-cba3afbce56c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div/div/div[2]/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d83c306-1afb-4adb-9c51-00d17ecdf215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.pcjeweller.com/user/printInvoice/id/71629</value>
      <webElementGuid>c440598c-8a66-4d5b-8214-5807f2edd93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e35ab61c-dafb-4627-abe8-f5b80e4273d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> print printInvoice</value>
      <webElementGuid>e1c61702-2001-4c26-ab9a-68739e5546ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Print Invoice</value>
      <webElementGuid>a2b48ad2-c7a0-44e6-bcd9-ba00d54b68c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>d3acb5f8-2cd7-4769-8dda-b7f66be0c06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-9 pull-right account-right&quot;]/div[@class=&quot;right-panel light-bg margin-bottom order-detail&quot;]/div[@class=&quot;order-top-sec clearfix hidden-xs&quot;]/div[@class=&quot;col-md-6 col-sm-6 col-xs-12 text-right&quot;]/a[@class=&quot;print printInvoice&quot;]</value>
      <webElementGuid>2a963387-505d-448a-9235-54c2a934d1d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>44df4b75-3bf5-498e-853b-55e8da517b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Print')]</value>
      <webElementGuid>51a08961-748e-4497-a018-5c4c8c5ee140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Order Details'])[1]/following::a[1]</value>
      <webElementGuid>0f1c52b3-432a-42ac-90ea-6d2a36057f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to My Order'])[1]/following::a[1]</value>
      <webElementGuid>3f26f339-25b5-4e38-9f99-baba5bcb874c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': 71629'])[1]/preceding::a[1]</value>
      <webElementGuid>eaa82d07-a075-491f-a1c0-25cc75852477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print']/parent::*</value>
      <webElementGuid>03151e05-2588-43fb-bb26-e15ec528fd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.pcjeweller.com/user/printInvoice/id/71629')]</value>
      <webElementGuid>e36a02f8-9ab1-41f1-bbc5-03e517a27265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>a16dd377-59d2-47b7-8da9-a818b2d8895c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.pcjeweller.com/user/printInvoice/id/71629' and @title = 'Print Invoice' and (text() = 'Print' or . = 'Print')]</value>
      <webElementGuid>24182fce-a8bf-48aa-964a-afea1664023d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
