<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fancybox__iframe_1_0, _9d6670</name>
   <tag></tag>
   <elementGuidId>5315ad9f-7b6e-453b-800a-70e9502f60ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox__iframe_1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox__iframe_1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4592b2f5-f890-4b25-825f-ac464f7eda6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox__iframe</value>
      <webElementGuid>c975608b-37b0-408e-b3b4-5365e9bbb607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox__iframe_1_0</value>
      <webElementGuid>6e001ff0-9516-4f57-8245-708fab145ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay; fullscreen</value>
      <webElementGuid>22b0bb06-ede4-4583-8824-c7e80d905252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>e259332c-7ee8-4245-a20f-a0db2a133591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.pcjeweller.com/user/printInvoice/id/71629</value>
      <webElementGuid>acf5d2a0-b77c-44cd-895e-2c2500b83af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f39f251-c050-4263-a6a8-d1168649a672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox__iframe_1_0&quot;)</value>
      <webElementGuid>3e0f36ca-c506-4e3c-9fce-a29ea8c1be0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox__iframe_1_0']</value>
      <webElementGuid>1924806c-fc7a-4798-9bc4-6d711a74839e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fancybox-1']/div[2]/div/div/div/div/iframe</value>
      <webElementGuid>150b9891-56c1-4226-b83f-cbf58d76a731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/iframe</value>
      <webElementGuid>fbbc8071-dcf3-41f6-abc6-f195ae45e994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox__iframe_1_0' and @src = 'https://www.pcjeweller.com/user/printInvoice/id/71629']</value>
      <webElementGuid>bc714fa1-44ef-4f43-ac7c-2af1c5964cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
