<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 Reviews</name>
   <tag></tag>
   <elementGuidId>796ece8a-0afe-463a-8e8b-9bddf4500326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='show-review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ddf591de-d707-496b-ad80-d7c27db3ac57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>83d1def7-f0aa-426c-9b6d-1cd9217b4d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-review</value>
      <webElementGuid>ffdbad1f-228a-4ad0-bed3-0367def026be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Reviews</value>
      <webElementGuid>1e3999c8-095f-4081-96e4-784197bfcea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-review&quot;)</value>
      <webElementGuid>d84373e0-a3be-429d-9d88-657f1fb7b96d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='show-review']</value>
      <webElementGuid>f7b8b4a0-abd1-4f48-add3-a185b2281a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[3]/div/div/ul/li/a</value>
      <webElementGuid>48b4c9da-f421-4644-a784-e4702c34cc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1 Reviews')]</value>
      <webElementGuid>f805e004-6b01-442e-8e7c-e46450b803c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OGCLG00001MM-UXY10'])[1]/following::a[1]</value>
      <webElementGuid>39f37054-3bb1-4054-9d30-32c9d9879136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold Coin'])[1]/preceding::a[1]</value>
      <webElementGuid>4986d23b-4f21-4861-a4e0-3fa8f77b3704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.R.P :'])[1]/preceding::a[1]</value>
      <webElementGuid>e421550c-7618-4f42-8f17-9133967312a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 Reviews']/parent::*</value>
      <webElementGuid>c8c2ab12-5482-4bb2-af8e-ccab3ee26876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Javascript:void(0);')])[9]</value>
      <webElementGuid>ca2727f4-e197-43f8-991c-ec80b8d9b66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li/a</value>
      <webElementGuid>77b158ab-53cb-4dc3-9155-855fed8ccfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'show-review' and (text() = '1 Reviews' or . = '1 Reviews')]</value>
      <webElementGuid>b872acca-f4c8-4d64-922a-b72facf530f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
