<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jewellery_wish-req</name>
   <tag></tag>
   <elementGuidId>48ee033e-14d9-4594-8964-49e4b41bade5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wish-req']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wish-req</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6a046b9-2286-4e3b-8ba1-9387d93cccb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>3b264055-899c-49f7-845f-064c961db780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-like wish-list</value>
      <webElementGuid>a2936c46-fbe1-44b1-acec-7e6a94a4b2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wish-req</value>
      <webElementGuid>24b88bee-54df-43d3-8e43-6b534295bfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wishlist</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>681d89ab-7b09-4ecc-ad2e-53005edb9a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>productid</name>
      <type>Main</type>
      <value>58585</value>
      <webElementGuid>06591a43-86d1-42b8-b488-3fb3f43f2a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user</name>
      <type>Main</type>
      <value>73324</value>
      <webElementGuid>8294873e-04f4-47c3-bbdc-42783b5c79d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wish-req&quot;)</value>
      <webElementGuid>c1453e80-aaf6-4e97-9079-b432dc0cea09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wish-req']</value>
      <webElementGuid>c6d23a01-08ba-4e65-81c7-39270a5fa2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>2ef14d87-e8ea-4c8d-a615-f7d77f4d0386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Javascript:void(0);')]</value>
      <webElementGuid>cda59204-b310-417a-aa67-c9ac09eb0a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>b9e65189-34f7-4216-a457-811c5294ae6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'wish-req']</value>
      <webElementGuid>f33f5dd8-baa2-40ea-89f4-de77bdb145e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
