<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Merchant Reviews_review_delete rewdlte ic_f067f4</name>
   <tag></tag>
   <elementGuidId>0dbb6773-6fde-484b-8cec-34f19b4eeac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='product']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.review_delete.rewdlte.icon-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4321a47-b866-4efb-a647-808ebf6441e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>424c0622-8e6b-419d-b555-f2c15526d499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>4c73a40a-b113-49e3-82d8-8b08023a503c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>031cc88a-f53c-4460-8b04-01cab65144ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>review_delete rewdlte icon-delete</value>
      <webElementGuid>95596003-b266-4323-9f99-fcd239663a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>5314e620-521b-4990-afbf-843936470059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTable1&quot;)/li[@class=&quot;prdt-review page1&quot;]/div[@class=&quot;pdt-details clearfix&quot;]/span[@class=&quot;pull-right&quot;]/a[@class=&quot;review_delete rewdlte icon-delete&quot;]</value>
      <webElementGuid>0ce58327-5ccd-4734-9198-4b23f1547d7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='product']</value>
      <webElementGuid>5fac768e-7a2e-469d-a6f8-0c81d2a249de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTable1']/li/div/span/a[2]</value>
      <webElementGuid>0618fe73-c17a-45d6-8d22-11f82f3c3316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Javascript:void(0);')]</value>
      <webElementGuid>33e7731f-77d6-488c-8d60-ae1ae507678f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a[2]</value>
      <webElementGuid>7a50e659-3aca-4d39-ad4b-cfc921a9f1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @type = 'product' and @title = 'Delete']</value>
      <webElementGuid>296b1bd2-c366-4b44-aff4-441fa9a8e1c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
