<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Deleted Successfully</name>
   <tag></tag>
   <elementGuidId>52a23fa7-7395-4963-876c-8b62d99a2f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='common_message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common_message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>edba58c8-3973-4138-8932-ff926ef23b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common_message</value>
      <webElementGuid>32bb023e-4f84-4f4c-8490-f462f45bfab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message_success</value>
      <webElementGuid>7b027ee5-e15c-4e0b-b698-b48170341a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deleted Successfully</value>
      <webElementGuid>1174b533-f8e8-4302-bc78-c105d06aca8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common_message&quot;)</value>
      <webElementGuid>15ffe662-e4df-48de-adb6-f30232a0f743</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='common_message']</value>
      <webElementGuid>25c86fa2-8e27-4e42-9ca0-922900fffc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div[2]/div/div</value>
      <webElementGuid>775f80c4-0f10-4734-b5a7-03dabc6a88bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Reviews'])[2]/following::div[1]</value>
      <webElementGuid>a549fe82-0598-4817-adff-b84e83ed993c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::div[3]</value>
      <webElementGuid>a24eed57-4444-45f3-8a5c-2fba296a4fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Reviews'])[1]/preceding::div[1]</value>
      <webElementGuid>eaacea59-d847-4df9-8d4d-29bf010a49b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant Reviews'])[1]/preceding::div[1]</value>
      <webElementGuid>d9585494-4382-4234-ae93-5957a682e214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deleted Successfully']/parent::*</value>
      <webElementGuid>d86f63e3-6ea6-4561-8164-46c272fac890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div</value>
      <webElementGuid>829880dd-e974-4c55-ab2c-80769cd0e15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'common_message' and (text() = 'Deleted Successfully' or . = 'Deleted Successfully')]</value>
      <webElementGuid>d15e148c-fdc3-4d1c-b229-32f903bd6e9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
