<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Updated Successfully</name>
   <tag></tag>
   <elementGuidId>16b4fe23-2589-4ffd-a601-0891651a5482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='common_message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common_message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>633e7a0e-8fa0-4fa4-a562-2b3f2c406fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common_message</value>
      <webElementGuid>78953a5f-aa1b-4e92-beeb-2d1c4e129b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message_success</value>
      <webElementGuid>394ea05e-d4a3-43c3-b18c-7f44b1d7567b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Updated Successfully</value>
      <webElementGuid>edb78d1a-bb55-491b-b28b-bc22f030c178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common_message&quot;)</value>
      <webElementGuid>6873725c-1521-45c5-9125-84bad7fb85e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='common_message']</value>
      <webElementGuid>dc659b2e-c764-496d-8664-0d1ce8d02c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div[2]/div/div</value>
      <webElementGuid>de8c1c52-f041-423f-98eb-8dbabf4ef407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Reviews'])[2]/following::div[1]</value>
      <webElementGuid>7d2779bf-1e22-4874-b0eb-3c3f46c1c129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::div[3]</value>
      <webElementGuid>e35ef703-274c-46a8-a093-87e7d6cf2ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Reviews'])[1]/preceding::div[1]</value>
      <webElementGuid>1f8ba790-9317-4b07-9d86-9cd96326cc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant Reviews'])[1]/preceding::div[1]</value>
      <webElementGuid>e54136f2-f5d9-4bfd-9beb-c6636848ed78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Updated Successfully']/parent::*</value>
      <webElementGuid>3a019f5f-fbd1-43fd-b21c-90e826dc5d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div</value>
      <webElementGuid>44c70168-1809-4dfd-80aa-a1ef2593ad4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'common_message' and (text() = 'Updated Successfully' or . = 'Updated Successfully')]</value>
      <webElementGuid>aabad91a-98a5-468f-84a1-0c0dc84d9237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
