<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Merchant Reviews_pull-right</name>
   <tag></tag>
   <elementGuidId>6aa317a5-1e35-49c2-877d-621ae269ad68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='myTable1']/li/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pdt-details.clearfix > span.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4a097ed-bcde-4795-8a05-d46b9cadbcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>1812ed8d-ce30-4594-9af1-a4a663b31d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTable1&quot;)/li[@class=&quot;prdt-review page1&quot;]/div[@class=&quot;pdt-details clearfix&quot;]/span[@class=&quot;pull-right&quot;]</value>
      <webElementGuid>9244a51e-cbbd-479d-b541-d1bc042c98b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTable1']/li/div/span</value>
      <webElementGuid>d3136e19-c41a-499d-b3a1-4dc06aabf96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant Reviews'])[1]/following::span[1]</value>
      <webElementGuid>692fe78d-35fb-47cd-8cd1-ebb44d1d6891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Reviews'])[1]/following::span[1]</value>
      <webElementGuid>01f3e70c-0fcb-4241-94c5-e2e337326069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Taksh Diamond Ring'])[1]/preceding::span[1]</value>
      <webElementGuid>d7893342-a096-4d36-bee2-5a9bf05cd52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rated 4/5'])[1]/preceding::span[2]</value>
      <webElementGuid>304a0e20-6e76-4de3-9869-4835e62444f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/span</value>
      <webElementGuid>df4a2d84-5315-453d-a4c9-5d9a2c806505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
