<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 Gram 24K Laxmi Ganesh Gold Coin</name>
   <tag></tag>
   <elementGuidId>f78da6e4-7b56-4702-b9c7-0a0ea3a01fd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='prodListingUl']/li[6]/div/div[2]/div/div/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d6dce29-c7ec-4c20-a485-ca9d2a1da8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/1-gram-24k-laxmi-ganesh-gold-coin.html?bid=MTIwNQ==</value>
      <webElementGuid>6cda8478-5bfe-4d15-95aa-159266d6beee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>38f554d1-1dd8-4e36-8de3-6dc61229f607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Gram 24K Laxmi Ganesh Gold Coin</value>
      <webElementGuid>69c79a38-9236-4861-abbb-ae572aab2409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prodListingUl&quot;)/li[@class=&quot;col-xs-6  col-lg-3 pdt-item-list&quot;]/div[@class=&quot;bx-contr&quot;]/div[@class=&quot;deatils pos-rel&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 title-section text-center ss&quot;]/div[@class=&quot;hidden-xs&quot;]/h2[@class=&quot;productTitle h5style font-medium rmv-padding text-overflow margin-bottom&quot;]/a[1]</value>
      <webElementGuid>2dd4f293-c194-4ccc-8129-eb3752798b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='prodListingUl']/li[6]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>b7b4a4aa-8514-4f2b-bb1e-b3d187e01ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1 Gram 24K Laxmi Ganesh Gold Coin')]</value>
      <webElementGuid>8d41f850-4a1a-43ac-9097-c78054255ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW DETAILS'])[11]/following::a[2]</value>
      <webElementGuid>a617658f-1bf0-4d6b-b39b-76ca292f18c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUY NOW'])[11]/following::a[3]</value>
      <webElementGuid>f866c200-ebc7-4536-9d9c-b4c9be74a93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹6,259'])[2]/preceding::a[1]</value>
      <webElementGuid>65d4bba4-cc01-4165-bd40-4af52b83f204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹6,314'])[2]/preceding::a[1]</value>
      <webElementGuid>2cf9dc3c-b869-4804-a574-a17787893af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 Gram 24K Laxmi Ganesh Gold Coin']/parent::*</value>
      <webElementGuid>e0830726-33dd-440b-b50f-42734be8121d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/1-gram-24k-laxmi-ganesh-gold-coin.html?bid=MTIwNQ==')])[3]</value>
      <webElementGuid>c26ccf88-2a3e-475b-a0c1-41922b983bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>a0f23d0c-eaab-4b14-828d-563b3dcdcb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/1-gram-24k-laxmi-ganesh-gold-coin.html?bid=MTIwNQ==' and (text() = '1 Gram 24K Laxmi Ganesh Gold Coin' or . = '1 Gram 24K Laxmi Ganesh Gold Coin')]</value>
      <webElementGuid>1aa2b374-15ae-4cc4-ab79-dcc3ad5754a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
