<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_20 Gram 24K Floral Gold Coin</name>
   <tag></tag>
   <elementGuidId>fd83faaf-c8d8-45d8-84a4-54169221fb51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='prodListingUl']/li[10]/div/div[2]/div/div/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c0b5bc9-c13c-4fbe-a3d4-4ab0fce5bef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/20-gram-24k-floral-gold-coin.html?bid=MTIwNQ==</value>
      <webElementGuid>a0039655-2f1f-4310-ab5c-a37cab142cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>3ba5e3f8-96b4-4ff6-9676-22b1dc0ac5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20 Gram 24K Floral Gold Coin</value>
      <webElementGuid>a0ef8b19-f006-4495-8fe7-466a6ae14f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prodListingUl&quot;)/li[@class=&quot;col-xs-6  col-lg-3 pdt-item-list&quot;]/div[@class=&quot;bx-contr&quot;]/div[@class=&quot;deatils pos-rel&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 title-section text-center ss&quot;]/div[@class=&quot;hidden-xs&quot;]/h2[@class=&quot;productTitle h5style font-medium rmv-padding text-overflow margin-bottom&quot;]/a[1]</value>
      <webElementGuid>50028a15-3aaa-430f-8619-a48cfde26807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='prodListingUl']/li[10]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>71ccac3e-f2e9-4fae-bc4e-8d992ea82e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'20 Gram 24K Floral Gold Coin')]</value>
      <webElementGuid>55c81375-3a3a-4981-aee5-16f2031c5aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW DETAILS'])[19]/following::a[2]</value>
      <webElementGuid>9578c280-5b5f-41c0-9f2a-c5fcad15c2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUY NOW'])[19]/following::a[3]</value>
      <webElementGuid>bba3f054-87a3-4920-ab47-96b6084ca9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹119,917'])[1]/preceding::a[1]</value>
      <webElementGuid>72b38041-2d7e-4f61-bdb3-0774b2706991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹121,128'])[1]/preceding::a[1]</value>
      <webElementGuid>8a88613f-2e89-4e70-92f7-ca1d18ccf77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20 Gram 24K Floral Gold Coin']/parent::*</value>
      <webElementGuid>41822b48-ef4e-4bbc-b493-2ff444f078ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/20-gram-24k-floral-gold-coin.html?bid=MTIwNQ==')])[3]</value>
      <webElementGuid>9a36c80b-9b96-4f0b-b97b-4dcc521555a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>737314ba-f0d3-4663-a012-4f78d49ccc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/20-gram-24k-floral-gold-coin.html?bid=MTIwNQ==' and (text() = '20 Gram 24K Floral Gold Coin' or . = '20 Gram 24K Floral Gold Coin')]</value>
      <webElementGuid>69680a82-f335-4c09-a25a-a8b435520e74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
