<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jewellery_wish-req</name>
   <tag></tag>
   <elementGuidId>b626fdb4-27b2-45f8-8a23-ab4ad34fcc65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wish-req</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wish-req']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02d1facb-8710-4a4d-ac10-8f8970eee686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>c9c6e808-3757-4e72-987d-046b2a62e3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-like wish-list</value>
      <webElementGuid>fd813565-ac73-4cfe-9fa7-3e295182b84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wish-req</value>
      <webElementGuid>83c52e70-1871-4863-a252-ca595e2ace21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wishlist</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2701c78c-a1de-4791-9612-acbe4109b7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>productid</name>
      <type>Main</type>
      <value>56273</value>
      <webElementGuid>fd79ee0f-a794-46d2-81d2-5b294522577e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wish-req&quot;)</value>
      <webElementGuid>f88dc999-3211-44f3-b075-7ad5d7489ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wish-req']</value>
      <webElementGuid>f3b9b8b4-9ef9-491d-a7e4-c1c3f00d149f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>c7684e54-9b43-4708-a3e8-ad12446bd017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Javascript:void(0);')])[3]</value>
      <webElementGuid>c4fbca9c-d281-4402-96b7-6037eeadca27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>68570149-b660-41df-8ed8-8799a2f60216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'wish-req']</value>
      <webElementGuid>904440f7-3093-42cc-9227-b18ebda6c039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
