<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Write Your Review</name>
   <tag></tag>
   <elementGuidId>4bda0262-7462-4a65-8aae-3054a9ee8388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.iconappend2.slip.write-review.popuplogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[3]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>baa21c97-2bce-4db3-8833-3fb945d6b17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productreview/id/56273</value>
      <webElementGuid>b8a48880-32fc-4404-b9cf-1e504f18f9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconappend2 slip write-review popuplogin</value>
      <webElementGuid>3a959598-017f-45d2-b304-43d9802c9d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>review</value>
      <webElementGuid>a02aca95-4363-4c5d-84b0-1ba2e730befc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>redirect</name>
      <type>Main</type>
      <value>productreview/id/56273</value>
      <webElementGuid>3415ec75-5d18-4947-8911-214abdcb5fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Write Your Review</value>
      <webElementGuid>c52e28eb-b172-474e-8a47-792bd7e28e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;clearfix&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;leftPanelOuter margin-bottom&quot;]/div[@class=&quot;light-bg sm-bg clearfix&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;productDetails col-xs-12 col-sm-6&quot;]/div[@class=&quot;light-bg inner-details&quot;]/div[@class=&quot;titleSec clearfix&quot;]/ul[@class=&quot;clearfix strip padding-top margin-bottom&quot;]/li[1]/a[@class=&quot;iconappend2 slip write-review popuplogin&quot;]</value>
      <webElementGuid>d1ba3e83-a410-4e20-a357-d0e7e7d8e0b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[3]/div/div/ul/li/a</value>
      <webElementGuid>c0683fca-8429-4611-bb9e-c41632652785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Write Your Review')]</value>
      <webElementGuid>028ab3ce-0833-4b3b-986a-c1213ce17a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GCH00140001'])[1]/following::a[1]</value>
      <webElementGuid>164b5c10-da60-4cea-9ac6-1d9373a4531c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PCJ - Solan, Himachal Pradesh'])[1]/following::a[1]</value>
      <webElementGuid>76994094-2764-4224-b234-6ee794c4054c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold Chain'])[2]/preceding::a[1]</value>
      <webElementGuid>f3828254-580b-4499-93f9-8653105ddb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.R.P :'])[1]/preceding::a[1]</value>
      <webElementGuid>ed867e78-f332-489f-b437-095dc66b9797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Write Your Review']/parent::*</value>
      <webElementGuid>a5724c0e-fc6c-4ba0-84c6-224cf039e3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productreview/id/56273')]</value>
      <webElementGuid>4b280b97-670a-4352-b1c2-b5da22b52a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li/a</value>
      <webElementGuid>94304389-9df3-4784-bc82-0ecf6ad2a551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productreview/id/56273' and (text() = 'Write Your Review' or . = 'Write Your Review')]</value>
      <webElementGuid>ee953cc3-4a32-422c-9464-6f56693cf789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
