<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Loading_loginPopup</name>
   <tag></tag>
   <elementGuidId>6e39929b-95bb-4a8e-aa2a-a33fe3dcb728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframeLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6a4060cc-a8d7-46f5-8a95-2a40d285ac67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeLogin</value>
      <webElementGuid>006bbf4d-d5fb-493b-9891-25380337184b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginPopup</value>
      <webElementGuid>684e6e5d-e88d-45a6-829b-807db2acbf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=productreview/id/56273</value>
      <webElementGuid>09b2f33a-44d1-4fc5-a303-a6c203a0266c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickpopup</value>
      <webElementGuid>5fa11710-cf9f-4aa4-af65-da01434089bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f99aa34-44c7-4d86-b1a7-ab6f824d6aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>19823cd9-5024-43ef-b256-935dd1bfbddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>48174061-81df-4c11-ba6f-fe7c44ebb3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e5d1dd58-b974-4ef4-8067-52bca4b5015f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0d66c285-efda-4155-8370-1cc60e5bcba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeLogin&quot;)</value>
      <webElementGuid>c26724c0-43c1-4b14-b5f8-87f055a6e649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeLogin']</value>
      <webElementGuid>e141f7d5-d0ca-469e-b163-ffa551eff183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/div/iframe</value>
      <webElementGuid>647fc7c4-b00f-43ae-9161-4f90f061ff0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Gifting'])[1]/preceding::iframe[1]</value>
      <webElementGuid>6ea185a5-8a9c-4a24-bfaf-3e063dea9db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>95b7cb59-4809-421d-b65b-e4cc70fa1fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeLogin' and @name = 'loginPopup' and @src = 'https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=productreview/id/56273']</value>
      <webElementGuid>0fc2a9c9-d175-4831-8c6f-c5c0bd308213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
