<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your changes have been saved successfully</name>
   <tag></tag>
   <elementGuidId>abec2cdd-58e2-467f-8af4-dda64ad10b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='common_message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common_message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9d896ca-ac76-4cc1-a028-b0923d62d58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common_message</value>
      <webElementGuid>b1740061-82ed-432f-be31-0eb35cd0d3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message_success</value>
      <webElementGuid>0dd5e264-6bea-425b-9b7a-237801e5755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your changes have been saved successfully.</value>
      <webElementGuid>05f3abf4-1884-4a3d-8328-4cf7776eb326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common_message&quot;)</value>
      <webElementGuid>e07f26b1-f984-46d7-bc19-7b8df3361bbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='common_message']</value>
      <webElementGuid>bab0fc5f-ea5f-4be0-b18a-828f4f842849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div[2]/div/div</value>
      <webElementGuid>bfcf699b-9564-4415-869a-5cd7ddfeb12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::div[1]</value>
      <webElementGuid>0a2e85d9-1b25-4512-a72a-167728a3fd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::div[3]</value>
      <webElementGuid>6927a287-6332-4fdd-9531-cfabe7f1af23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address :'])[1]/preceding::div[1]</value>
      <webElementGuid>5bacd70f-117c-43a2-91de-c79b3f60b02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='draftcardtesting1@gmail.com'])[1]/preceding::div[1]</value>
      <webElementGuid>ab71f64e-7ff9-477a-9eea-0f473e27c0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your changes have been saved successfully.']/parent::*</value>
      <webElementGuid>8d957be3-c7b2-488c-995f-02da19585a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div</value>
      <webElementGuid>2d8e5368-3575-4d43-86fa-b66e7545e342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'common_message' and (text() = 'Your changes have been saved successfully.' or . = 'Your changes have been saved successfully.')]</value>
      <webElementGuid>46543d4a-6892-4eb6-a9de-1bc6b1afd108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
