<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ring</name>
   <tag></tag>
   <elementGuidId>9b2b2672-b167-412e-917a-fce9aaf741c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body</value>
      <webElementGuid>ac579e17-ea08-47ec-a99e-dd1588a71652</webElementGuid>
   </webElementProperties>
</WebElementEntity>
