<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Date12345678910111213141516171819202_49f153</name>
   <tag></tag>
   <elementGuidId>e7ba53cd-27ed-4eff-8aee-0cf7c3955610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dobDay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dobDay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fe3915d4-b76d-48e3-80dc-103e4e923d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c8a1c3aa-7b9d-49b3-b1b8-5c271b366719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  dob-valid</value>
      <webElementGuid>295a5805-eba0-4d39-9544-6d95d43c4027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dobDay</value>
      <webElementGuid>e1fba62b-011b-4613-98e2-494a8c2de8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dobDay</value>
      <webElementGuid>89c7684e-49fc-4251-b31b-0f9d0bbe87d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>be9f6771-6fca-4d26-99c1-fc7e1ddf53bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dobDay&quot;)</value>
      <webElementGuid>5f7b45b4-03dd-4f09-a1a7-826530c0a22d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dobDay']</value>
      <webElementGuid>6e89e300-8451-4004-91db-2c95b467af35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formUserProfileEdit']/fieldset/div/div/div[4]/div/div/div/div/select</value>
      <webElementGuid>03d1e7d8-1b9c-4c5e-a368-87265adb847e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>504d7953-a384-47a3-bb4b-2a093f398de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required~*Enter Valid Date'])[1]/preceding::select[1]</value>
      <webElementGuid>af5cfbf1-526f-45aa-a889-520e3905bc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required~*Enter Valid Month'])[1]/preceding::select[2]</value>
      <webElementGuid>ef784442-ef9b-425c-9bce-7cbd6cfbeab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3fa7ea77-4b57-4c1a-a51c-52bf9ce1f356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dobDay' and @name = 'dobDay' and (text() = 'Date12345678910111213141516171819202122232425262728293031' or . = 'Date12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>1e428676-fd17-4e63-9d54-9b11dd8df3e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
