<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Write a Comment_submitReviewComment</name>
   <tag></tag>
   <elementGuidId>efede4f1-c171-4eec-b83d-dda176a90476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitReviewComment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitReviewComment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>923dbb37-bf47-489b-ac6a-711b4f114f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8141b1b4-b46c-4005-9e1a-c2a4b11ea779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitReviewComment</value>
      <webElementGuid>21ba6d44-c323-4a02-bb44-567837159923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>888157bc-ac0d-4327-8217-f891eb2f3ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>8b53b94f-c330-4c8b-a1ee-ddd0b6b5aadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d9eda9dd-e9e6-44be-b637-05fe6adf6b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitReviewComment</value>
      <webElementGuid>e65a8719-6da3-4458-9ef8-9bb684b65786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitReviewComment&quot;)</value>
      <webElementGuid>89b94ff1-f7b1-4cd2-8d01-76b4d6042c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitReviewComment']</value>
      <webElementGuid>36f0222b-609e-45e2-aaf7-1caa35447c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditReview']/ul/li[5]/div/input</value>
      <webElementGuid>50f9201f-802d-4d06-a15d-475c10ba38cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/input</value>
      <webElementGuid>1389ef61-120d-4878-af1e-6f486b964eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submitReviewComment' and @id = 'submitReviewComment']</value>
      <webElementGuid>6be9e7d6-b85a-48e7-b445-9628a2f26970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
