<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please give the product a star rating_fa4289</name>
   <tag></tag>
   <elementGuidId>e4e50c05-9fe3-4c7a-9d28-249835fee34c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='productReviewTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productReviewTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2fab4cd-0565-4325-a9fa-30fe0b311fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bc1f8af-146c-4fea-a987-f733fe078170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>productReviewTitle</value>
      <webElementGuid>f3cce353-b954-40ad-93f8-e42447236785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>689ee028-a26f-4887-af93-ac969c6d344a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>daff8c22-c811-4261-af8c-3df8cd6d36a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>6a06de67-a9bc-4a2c-9638-5f52ff73e2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productReviewTitle</value>
      <webElementGuid>a8a94837-af73-40a3-a9e3-8ab802a2e25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productReviewTitle&quot;)</value>
      <webElementGuid>d056a921-da7a-448b-9edb-f1cff4c2e5c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='productReviewTitle']</value>
      <webElementGuid>b39c30fc-293b-4751-9d36-b0bd6a716c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditReview']/ul/li[3]/div[2]/input</value>
      <webElementGuid>8f327d0c-fed1-4c4e-b8a4-26499d092754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>13423d92-4139-4362-900a-f89b0ed90d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'productReviewTitle' and @id = 'productReviewTitle']</value>
      <webElementGuid>d9fca32a-45d5-40d7-a894-baaeabbbae01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
