<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go To Details</name>
   <tag></tag>
   <elementGuidId>4d1a8c16-2d37-4aed-87d1-e838e0b59781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.btn-sm.wish-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edfdbd32-6830-4dfc-9b71-cea8bab955c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/the-naveah-diamond-ring.html</value>
      <webElementGuid>7f891c21-b31a-42d1-b954-2b1f8891a3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm wish-btn</value>
      <webElementGuid>fd9def1b-8bdd-41d8-88b0-336d3bac27ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>4ab390e8-2606-49db-9f22-1b8a0d27f245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go To Details</value>
      <webElementGuid>ed8947a7-18e9-4722-b83d-275e57e49176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-9&quot;]/div[@class=&quot;right-panel light-bg&quot;]/div[@class=&quot;my-wishlist&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-4 col-md-4 wishlist&quot;]/div[@class=&quot;wishlist_bx&quot;]/div[@class=&quot;details&quot;]/div[@class=&quot;clearfix margin-bottom&quot;]/a[@class=&quot;btn btn-default btn-sm wish-btn&quot;]</value>
      <webElementGuid>11f2aa4a-42f0-41c2-8d50-f2472c9535a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div[3]/a</value>
      <webElementGuid>e1ca9bb5-14e5-476e-a1d5-02eb9ee9a899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go To Details')]</value>
      <webElementGuid>46f21266-3e1a-48f8-bc70-f1c31895a8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹8,636'])[1]/following::a[1]</value>
      <webElementGuid>5dbfe7fd-999b-4f98-b57d-ebe0112d9136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(5/5)'])[1]/following::a[1]</value>
      <webElementGuid>d3dc56e0-7c9f-421c-a8a1-2505e0f681e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The My Brother My Hero Silver Rakhi'])[1]/preceding::a[1]</value>
      <webElementGuid>022f1d65-4ea8-4ace-a282-22233ef99997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(5/5)'])[2]/preceding::a[1]</value>
      <webElementGuid>e64ca0a8-da8e-48e6-b0e3-5114013ebc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go To Details']/parent::*</value>
      <webElementGuid>bf4f9a73-c46e-4036-9862-09cd6469f5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/the-naveah-diamond-ring.html')]</value>
      <webElementGuid>d7389ae7-cf7d-4b89-932d-e7742363f68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a</value>
      <webElementGuid>53b9e239-a978-440c-9861-e26d9b7387ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/the-naveah-diamond-ring.html' and (text() = 'Go To Details' or . = 'Go To Details')]</value>
      <webElementGuid>a10e3bbf-2470-4cfe-88e9-eeedfa830efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
