<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Wishlist_wish-closeBtn</name>
   <tag></tag>
   <elementGuidId>b94f7e11-c181-4639-aea5-150ce65b6910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wish-closeBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wish-closeBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c996a5a6-d421-463d-8f30-fcefb76f4602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>closeBtn3 icon-delete</value>
      <webElementGuid>14a9f9da-dc4a-4e3a-b32b-4970c1757b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wish-closeBtn</value>
      <webElementGuid>01c3185f-64ae-4110-a409-fa23547f72de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemid</name>
      <type>Main</type>
      <value>144330</value>
      <webElementGuid>8e905d25-7c18-413b-aae4-195e324c87eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-9&quot;]/div[@class=&quot;right-panel light-bg&quot;]/div[@class=&quot;my-wishlist&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-4 col-md-4 wishlist&quot;]/div[@id=&quot;wish-closeBtn&quot;]</value>
      <webElementGuid>471ef698-9ee0-4af6-9cdf-abf8f56e958c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wish-closeBtn']</value>
      <webElementGuid>4a94135c-d644-40b0-b956-19bd6fc16f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>6052290e-f84a-44d0-bf1d-dabcf24e78a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>b3506d2a-0c98-4676-be9c-5a051cee097f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wish-closeBtn']</value>
      <webElementGuid>acf28ea0-1006-4128-a730-c007de5f5c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
