<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Shipping Details Updated</name>
   <tag></tag>
   <elementGuidId>d896d406-fc97-4bc6-ace6-37dcf56192f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='common_message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common_message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f702a8b6-8c75-4220-ba10-252543dca473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common_message</value>
      <webElementGuid>48d9a16a-a729-4f57-bca1-0e1e012b6d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message_info</value>
      <webElementGuid>233c42c9-a7f9-491d-aa78-23336380ad5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipping Details Updated.</value>
      <webElementGuid>cdc860e4-74a8-4579-9865-70f6b20d7ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common_message&quot;)</value>
      <webElementGuid>f4631f4d-6fac-43e7-957d-62718d13d9b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='common_message']</value>
      <webElementGuid>0bc29395-35a6-4631-8643-a7bf855bb16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div[2]/div/div</value>
      <webElementGuid>f5eb703e-78a6-4b60-897e-d20bee39b5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose any one to make it primary'])[1]/following::div[1]</value>
      <webElementGuid>fd344a1f-26e4-440a-98c0-8e2ac0520ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remo , Address 1, Maharashtra, pune, Test, India'])[1]/preceding::div[2]</value>
      <webElementGuid>1e94db8b-fbe9-4cb1-965e-5e3d2cb7dabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Address'])[1]/preceding::div[4]</value>
      <webElementGuid>62a0f0a9-2cc3-486a-9a84-4dbc60b487c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipping Details Updated.']/parent::*</value>
      <webElementGuid>21039e0e-626f-438c-aee4-28c8b61829f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div</value>
      <webElementGuid>8381c281-4765-429a-b164-4ef17dedf7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'common_message' and (text() = 'Shipping Details Updated.' or . = 'Shipping Details Updated.')]</value>
      <webElementGuid>4fc29656-6b03-4f93-8f01-69489671e009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
