<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Make this my primary shipping address</name>
   <tag></tag>
   <elementGuidId>23b485f6-9669-4790-950d-7962e0cdde52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formUserShippingEdit']/div[5]/div/div/p/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.primaryCheck > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bafc6833-bc66-48fb-bd08-7844fec06cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>makeAddressAsPrimary</value>
      <webElementGuid>9ec5a1a1-b5fe-4c26-8236-56c74ef37f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Make this my primary shipping address</value>
      <webElementGuid>5b738b0f-2c50-4d6b-9de5-84ff8aa39f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formUserShippingEdit&quot;)/div[@class=&quot;clearfix&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/p[@class=&quot;primaryCheck&quot;]/label[1]</value>
      <webElementGuid>3e47f809-c6c7-4ca8-ad40-9a25ad78bbf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formUserShippingEdit']/div[5]/div/div/p/label</value>
      <webElementGuid>d67f31fa-860c-4ca0-b0ba-2182c628cc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Pin Code'])[1]/following::label[1]</value>
      <webElementGuid>1c9ee2f3-540c-4481-a7d8-ebf88090b6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::label[1]</value>
      <webElementGuid>543d0e01-0c2b-4f84-869a-8cce4fc5aa91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cancel'])[1]/preceding::label[1]</value>
      <webElementGuid>9c372374-3a72-46d7-95a1-8bff8c75efa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP WITHOUT WORRY'])[1]/preceding::label[1]</value>
      <webElementGuid>302d6837-3db1-46d4-a303-e10d348f6cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Make this my primary shipping address']/parent::*</value>
      <webElementGuid>e3d65293-1862-4f6d-96e9-da062c9260f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/label</value>
      <webElementGuid>911de848-53a5-4d4e-92c2-234aa2574ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Make this my primary shipping address' or . = 'Make this my primary shipping address')]</value>
      <webElementGuid>f8b9b5ca-bbff-440f-ab44-269b4ae3c124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
