<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 Reviews</name>
   <tag></tag>
   <elementGuidId>6ce9a286-bcc7-459d-8c3b-dfc59ed73470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='show-review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2567ad3-85dc-4c35-bedc-b982dbad0e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>502bb4ce-2ee5-4fab-9720-770f8a84c4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-review</value>
      <webElementGuid>4b205d13-0e52-4614-8acb-294980f4bbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Reviews</value>
      <webElementGuid>32536b89-e56b-437e-bbd8-c46fc6131eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-review&quot;)</value>
      <webElementGuid>96ccedda-08e5-47d4-a955-517b9965af9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='show-review']</value>
      <webElementGuid>c41412d3-f902-4674-8a66-535b8768ba9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[3]/div/div/ul/li/a</value>
      <webElementGuid>5fdaa4f6-9d90-4836-9d20-288dd9b9b053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1 Reviews')]</value>
      <webElementGuid>ebcf786b-9b09-45ff-8ff9-718b6af2afca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OGCFL00020MM-UXY10'])[1]/following::a[1]</value>
      <webElementGuid>168af088-0bed-420e-a7ae-1ed2955d0b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.R.P :'])[1]/preceding::a[1]</value>
      <webElementGuid>3e68b549-aef0-4060-8ede-23204663a1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Inclusive of all taxes)'])[1]/preceding::a[1]</value>
      <webElementGuid>ba00bc5a-caa6-4fed-9c4d-c8bb4c20fbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 Reviews']/parent::*</value>
      <webElementGuid>06e7c3f2-6786-40a3-82a2-571689d12712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Javascript:void(0);')])[9]</value>
      <webElementGuid>bd70e454-be07-4a4a-8f4f-b01de7703725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li/a</value>
      <webElementGuid>3db3cec5-cc3e-487b-a84a-8b2b0aa76a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'show-review' and (text() = '1 Reviews' or . = '1 Reviews')]</value>
      <webElementGuid>c9a49cc9-ddf7-4ae2-984a-8ebc370d3840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
