<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Loading_loginPopup</name>
   <tag></tag>
   <elementGuidId>d8be4304-eb64-408b-af7f-2f3dc8b5e47a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframeLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2bdad34b-4390-46df-a2e6-2b8ab98516f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeLogin</value>
      <webElementGuid>a59af18f-b611-4931-a6ab-32a8280c85e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginPopup</value>
      <webElementGuid>22327540-7532-43a1-811f-b78cdb17475b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=productreview/id/24306</value>
      <webElementGuid>0c96c73a-39b5-446f-a529-317b2b6a598d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickpopup</value>
      <webElementGuid>4c8cfdc2-d87f-4dfc-b6e5-81e5e7290cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07e8f789-21ee-4ae2-910c-fb5f9d8de5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>2a1a93ae-0be6-41d4-b118-8405ce558b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>532f1b93-cff3-46f1-9c09-3eed6d814333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3e4c6d8b-9d42-4ce0-8c01-e22ec61550b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4b7f3332-f78b-413f-b046-516967952d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeLogin&quot;)</value>
      <webElementGuid>8b2cc761-5345-403b-ab74-b112ac346620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeLogin']</value>
      <webElementGuid>22ed269a-92fa-41df-b782-da15abea718e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/div/iframe</value>
      <webElementGuid>2471044f-67db-4e75-840e-09a5f1caeb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Gifting'])[1]/preceding::iframe[1]</value>
      <webElementGuid>6ecac7ab-8042-4f2d-b47e-6a601cb2b5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>64cac924-4fb4-45b5-94cd-8b85a3e0e0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeLogin' and @name = 'loginPopup' and @src = 'https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=productreview/id/24306']</value>
      <webElementGuid>7e749000-699c-437f-b610-8d7ce9ba832b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
