<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_earrings_wish-req</name>
   <tag></tag>
   <elementGuidId>2e243f07-131d-4842-b4a1-0cb2531498aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wish-req']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wish-req</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bfbadfe4-c0c9-4ec9-ab72-bbd876b095bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>50298a16-5bb9-4ac3-a034-7f6ab214f463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-like wish-list</value>
      <webElementGuid>1a12a2c1-f3dc-4de0-964e-3c82add364d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wish-req</value>
      <webElementGuid>8f99f394-dffa-4a1e-a389-b49dd9dfbfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wishlist</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f4299aa1-ef00-4b3a-b6b0-f778b7e91f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>productid</name>
      <type>Main</type>
      <value>27370</value>
      <webElementGuid>8cd4b2cd-0ebf-406d-8c3f-b0f5ac47e93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user</name>
      <type>Main</type>
      <value>73324</value>
      <webElementGuid>e31e4cf3-7100-402a-878d-38a8d58b5b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wish-req&quot;)</value>
      <webElementGuid>d9a44b63-063c-40df-b784-de13c5629a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wish-req']</value>
      <webElementGuid>00d6fb03-2e2a-4ecd-8de2-0691cb693519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>ebb340ef-251e-4363-819f-e952963762b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Javascript:void(0);')]</value>
      <webElementGuid>cef4cd20-ee2e-4685-a6d2-5e32f3d9f63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>4e4c5413-157a-44b7-9a33-da82783a8685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'wish-req']</value>
      <webElementGuid>cbc8447c-a3ee-46b9-a696-6605519bc219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
