<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a386abea-c87f-43f5-8eb2-10f45d6cb1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo']/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.img-responsive.hidden-xs.hidden-sm > img[alt=&quot;PCJeweller&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>863bddcc-7e6b-4bbd-b28d-c2854ae625cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cf-cdn.pcjeweller.com/public/uploads/settings/pcj-logo__592261435__1103462098.png</value>
      <webElementGuid>8717e2c8-b67d-424c-8aa8-82d1c685478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa34de02-68b7-451f-a1c3-b93ef80abdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>PCJeweller</value>
      <webElementGuid>bb334082-d59b-4abe-b5c8-fb0b14a1d045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>08ef7f4f-4e51-4932-9aea-d6b26b54c453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/a[@class=&quot;img-responsive hidden-xs hidden-sm&quot;]/img[1]</value>
      <webElementGuid>1c5c6e20-47ff-4c45-90f7-14f807de45e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo']/a/img</value>
      <webElementGuid>6a7f9024-0c45-4cd8-83e3-bbc1c06c6493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='PCJeweller'])[2]</value>
      <webElementGuid>f6a8050a-0910-4c7f-900c-14b8cc20372e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a/img</value>
      <webElementGuid>8323f42f-ba76-42ef-8bfc-a064474ee84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cf-cdn.pcjeweller.com/public/uploads/settings/pcj-logo__592261435__1103462098.png' and @alt = 'PCJeweller']</value>
      <webElementGuid>224ec52a-9f25-4691-996b-149c9bac8a3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
