<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Loading_loginPopup</name>
   <tag></tag>
   <elementGuidId>a9a1cbbd-c666-413e-a012-4b4b052e8e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframeLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ac8bb349-1fdd-4f8e-86ac-f88f13ece9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeLogin</value>
      <webElementGuid>127d0441-5fff-4e9e-be8d-ae463b01d586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginPopup</value>
      <webElementGuid>f21e6c35-8085-4eb7-b6be-8cf03b1701d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=productreview/id/54418</value>
      <webElementGuid>02af72c3-7ff7-41ba-a35b-9bc4cade997f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickpopup</value>
      <webElementGuid>a3332328-ef3b-4f64-a3f2-abf6b75ede11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>81005ef1-6fc4-4b32-a918-fddd93c099c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>48ac1fd9-5eb6-433e-b8ab-b71c943d371c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>03e17791-3490-4c2b-bdc1-b2a0587eab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e3cd1138-4272-454c-a977-126104581eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>aac8231d-a184-42b2-a4a2-fee8af13900f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeLogin&quot;)</value>
      <webElementGuid>ba687667-4d19-4429-8eec-551f49442d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeLogin']</value>
      <webElementGuid>68a3d284-3851-4b66-a487-113201aa187e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/div/iframe</value>
      <webElementGuid>33ad400e-9cf8-420f-8bfc-db2e331e1f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Gifting'])[1]/preceding::iframe[1]</value>
      <webElementGuid>506a8db6-f7fe-4384-9a87-48cbfa4d0be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4ae606bd-0f23-4b03-84d4-f32107da588a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeLogin' and @name = 'loginPopup' and @src = 'https://www.pcjeweller.com/login/ajaxPopupLogin/?reurl=productreview/id/54418']</value>
      <webElementGuid>0f678ac0-36df-4f7b-bb4b-f4bb7b9e8f58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
