<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectIndiaUnited Arab EmiratesUnite_d26500</name>
   <tag></tag>
   <elementGuidId>0956266a-d88c-4b68-8094-dc65203a09d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='countryID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#countryID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de3bc56c-ab20-4b6d-8b41-f4b729fcfea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c48a8230-e848-4c59-8468-f676c7ce3d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>523a283e-c049-427a-b579-795912124da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; listStates(this.value,'');</value>
      <webElementGuid>a9ff40c2-e838-49d7-a91e-1c5c45ae8000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countryID</value>
      <webElementGuid>47b49a7e-f7a8-49d1-bbd0-46cd7cb9f347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>countryID</value>
      <webElementGuid>c67dd6f3-120e-4f33-866e-b9fc6aecb4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectIndiaUnited Arab EmiratesUnited StatesEnglandAustraliaCanadaAfghanistanAlbaniaAlgeriaAmerican SamoaAndorraAngolaAntarcticaAntigua and BarbudaArgentinaArmeniaArubaAustriaAzerbaijanAzoresBahamasBahrainBangladeshBarbadosBarbudaBelarusBelgiumBelizeBeninBermudaBhutanBoliviaBonaireBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaBurkina FasoBurundiCambodiaCameroonCanary IslandsCape VerdeCayman IslandsCentral African RepublicChadChannel IslandsChileChinaChristmas IslandCocos (Keeling) IslandsColombiaComorosCook IslandsCosta RicaCote D'IvoireCroatia (Hrvatska)CubaCuracaoCyprusCzech RepublicDenmarkDjiboutiDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland Islands (Malvinas)Faroe IslandsFederated States Of MicronesiaFijiFinlandFranceFranceFrench GuianaFrench PolynesiaFrench Southern TerritoriesGabonGambiaGeorgiaGermanyGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard Island, McDonald IslandsHondurasHong KongHungaryIcelandIndonesiaIraqIrelandIslamic Republic of IranIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao People's Democratic RepublicLatviaLebanonLesothoLiberiaLibyan Arab JamahiriyaLiechtensteinLithuaniaLuxembourgMacauMadagascarMadeiraMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMonacoMongoliaMontserratMoroccoMozambiqueMyanmarNamibiaNauruNepalNequeNetherlandsNetherlands AntillesNew CaledoniaNew ZealandNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPalestinian TerritoriesPanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPonapePortugalPuerto RicoQatarRepublic of CongoRepublic of CongoRepublic Of KoreaRepublic Of MoldovaReunionRomaniaRotaRussian FederationRwandaSabaSaint Kitts and NevisSaint LuciaSaint Vincent and The GrenadinesSaipanSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaScotlandSenegalSeychellesSierra LeoneSingaporeSlovakia (Slovak Republic)SloveniaSolomon IslandsSomaliaSouth AfricaSouth Georgia and The South Sandwich IslandsSpainSri LankaSt. BarthelemySt. ChristopherSt. CroixSt. EustatiusSt. HelenaSt. JohnSt. MaartenSt. MartinSt. Pierre and MiquelonSt. ThomasSudanSurinameSvalbard and Jan Mayen IslandsSwazilandSwedenSwitzerlandSyrian Arab RepublicTahitiTaiwanTajikistanThailandThe Former Yugoslav Republic Of MacedoniaTinianTogoTokelauTongaTrinidad and TobagoTrukTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited KingdomUnited Republic Of TanzaniaUnited States Minor Outlying IslandsUruguayUzbekistanVanuatuVatican CityVenezuelaViet NamVirgin Islands (British)Virgin Islands (U.S.)Wake IslandWalesWallis and Futuna IslandsWestern SaharaYapYemenYugoslaviaZaireZambiaZimbabwe</value>
      <webElementGuid>40720932-6f6b-4118-8de8-7f1449d212d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countryID&quot;)</value>
      <webElementGuid>b76a9e05-8537-4106-ba95-86fa5866d2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='countryID']</value>
      <webElementGuid>91658634-5a36-4e5e-b5e9-ef48db14cfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formaddress']/fieldset/div/div[2]/div[4]/div/select</value>
      <webElementGuid>4de96232-0265-41ac-87f6-9729645658b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>0a989276-0e79-4bca-92ea-d1b9f899337c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Country from the list'])[1]/preceding::select[1]</value>
      <webElementGuid>9d8e53ef-fe21-432e-b358-22174fb63b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0abd5e30-1d8c-4149-8539-5995a25b745b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'countryID' and @name = 'countryID' and (text() = concat(&quot;SelectIndiaUnited Arab EmiratesUnited StatesEnglandAustraliaCanadaAfghanistanAlbaniaAlgeriaAmerican SamoaAndorraAngolaAntarcticaAntigua and BarbudaArgentinaArmeniaArubaAustriaAzerbaijanAzoresBahamasBahrainBangladeshBarbadosBarbudaBelarusBelgiumBelizeBeninBermudaBhutanBoliviaBonaireBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaBurkina FasoBurundiCambodiaCameroonCanary IslandsCape VerdeCayman IslandsCentral African RepublicChadChannel IslandsChileChinaChristmas IslandCocos (Keeling) IslandsColombiaComorosCook IslandsCosta RicaCote D&quot; , &quot;'&quot; , &quot;IvoireCroatia (Hrvatska)CubaCuracaoCyprusCzech RepublicDenmarkDjiboutiDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland Islands (Malvinas)Faroe IslandsFederated States Of MicronesiaFijiFinlandFranceFranceFrench GuianaFrench PolynesiaFrench Southern TerritoriesGabonGambiaGeorgiaGermanyGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard Island, McDonald IslandsHondurasHong KongHungaryIcelandIndonesiaIraqIrelandIslamic Republic of IranIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLatviaLebanonLesothoLiberiaLibyan Arab JamahiriyaLiechtensteinLithuaniaLuxembourgMacauMadagascarMadeiraMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMonacoMongoliaMontserratMoroccoMozambiqueMyanmarNamibiaNauruNepalNequeNetherlandsNetherlands AntillesNew CaledoniaNew ZealandNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPalestinian TerritoriesPanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPonapePortugalPuerto RicoQatarRepublic of CongoRepublic of CongoRepublic Of KoreaRepublic Of MoldovaReunionRomaniaRotaRussian FederationRwandaSabaSaint Kitts and NevisSaint LuciaSaint Vincent and The GrenadinesSaipanSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaScotlandSenegalSeychellesSierra LeoneSingaporeSlovakia (Slovak Republic)SloveniaSolomon IslandsSomaliaSouth AfricaSouth Georgia and The South Sandwich IslandsSpainSri LankaSt. BarthelemySt. ChristopherSt. CroixSt. EustatiusSt. HelenaSt. JohnSt. MaartenSt. MartinSt. Pierre and MiquelonSt. ThomasSudanSurinameSvalbard and Jan Mayen IslandsSwazilandSwedenSwitzerlandSyrian Arab RepublicTahitiTaiwanTajikistanThailandThe Former Yugoslav Republic Of MacedoniaTinianTogoTokelauTongaTrinidad and TobagoTrukTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited KingdomUnited Republic Of TanzaniaUnited States Minor Outlying IslandsUruguayUzbekistanVanuatuVatican CityVenezuelaViet NamVirgin Islands (British)Virgin Islands (U.S.)Wake IslandWalesWallis and Futuna IslandsWestern SaharaYapYemenYugoslaviaZaireZambiaZimbabwe&quot;) or . = concat(&quot;SelectIndiaUnited Arab EmiratesUnited StatesEnglandAustraliaCanadaAfghanistanAlbaniaAlgeriaAmerican SamoaAndorraAngolaAntarcticaAntigua and BarbudaArgentinaArmeniaArubaAustriaAzerbaijanAzoresBahamasBahrainBangladeshBarbadosBarbudaBelarusBelgiumBelizeBeninBermudaBhutanBoliviaBonaireBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaBurkina FasoBurundiCambodiaCameroonCanary IslandsCape VerdeCayman IslandsCentral African RepublicChadChannel IslandsChileChinaChristmas IslandCocos (Keeling) IslandsColombiaComorosCook IslandsCosta RicaCote D&quot; , &quot;'&quot; , &quot;IvoireCroatia (Hrvatska)CubaCuracaoCyprusCzech RepublicDenmarkDjiboutiDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland Islands (Malvinas)Faroe IslandsFederated States Of MicronesiaFijiFinlandFranceFranceFrench GuianaFrench PolynesiaFrench Southern TerritoriesGabonGambiaGeorgiaGermanyGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard Island, McDonald IslandsHondurasHong KongHungaryIcelandIndonesiaIraqIrelandIslamic Republic of IranIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLatviaLebanonLesothoLiberiaLibyan Arab JamahiriyaLiechtensteinLithuaniaLuxembourgMacauMadagascarMadeiraMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMonacoMongoliaMontserratMoroccoMozambiqueMyanmarNamibiaNauruNepalNequeNetherlandsNetherlands AntillesNew CaledoniaNew ZealandNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPalestinian TerritoriesPanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPonapePortugalPuerto RicoQatarRepublic of CongoRepublic of CongoRepublic Of KoreaRepublic Of MoldovaReunionRomaniaRotaRussian FederationRwandaSabaSaint Kitts and NevisSaint LuciaSaint Vincent and The GrenadinesSaipanSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaScotlandSenegalSeychellesSierra LeoneSingaporeSlovakia (Slovak Republic)SloveniaSolomon IslandsSomaliaSouth AfricaSouth Georgia and The South Sandwich IslandsSpainSri LankaSt. BarthelemySt. ChristopherSt. CroixSt. EustatiusSt. HelenaSt. JohnSt. MaartenSt. MartinSt. Pierre and MiquelonSt. ThomasSudanSurinameSvalbard and Jan Mayen IslandsSwazilandSwedenSwitzerlandSyrian Arab RepublicTahitiTaiwanTajikistanThailandThe Former Yugoslav Republic Of MacedoniaTinianTogoTokelauTongaTrinidad and TobagoTrukTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited KingdomUnited Republic Of TanzaniaUnited States Minor Outlying IslandsUruguayUzbekistanVanuatuVatican CityVenezuelaViet NamVirgin Islands (British)Virgin Islands (U.S.)Wake IslandWalesWallis and Futuna IslandsWestern SaharaYapYemenYugoslaviaZaireZambiaZimbabwe&quot;))]</value>
      <webElementGuid>818e431c-f04b-4c97-a276-cf51614c7bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
