<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jewellery_wish-req</name>
   <tag></tag>
   <elementGuidId>1c22292e-0881-4a11-93bf-8cd954f0500a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wish-req</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wish-req']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89852559-bf05-4275-9dfb-283e58b5d860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>a86d0a2c-7af1-4f8f-9ea7-e45a29f8aa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-like wish-list</value>
      <webElementGuid>04c63ae4-05e4-46cc-a9c5-b7e07cf96bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wish-req</value>
      <webElementGuid>20bc142c-fe34-4ead-894b-8867cc6674d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wishlist</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eef4243c-2b67-481c-9bf6-f7005a34b0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>productid</name>
      <type>Main</type>
      <value>42610</value>
      <webElementGuid>90ff3917-53bf-4311-b9cb-f3abc1ac51ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wish-req&quot;)</value>
      <webElementGuid>44c9fbc3-8767-4987-8dfb-5b6895c440c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wish-req']</value>
      <webElementGuid>f4fde528-7537-4bae-9aa9-dd6823523d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>05c092fc-5f2c-4250-8af1-432f5331730e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Javascript:void(0);')])[3]</value>
      <webElementGuid>895b1474-5fea-407e-b928-6c3064656dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>8c63b218-55f2-4569-8f3c-3b02e4871e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'wish-req']</value>
      <webElementGuid>e77a4842-6613-4e1e-93e6-d3521d8a434b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
