<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Earrings</name>
   <tag></tag>
   <elementGuidId>553ace41-5128-4ddf-980c-e0f1923718bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b877a9f-ceca-4e4e-acba-4e7361f2eeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jewellery/earrings.html</value>
      <webElementGuid>54f0baca-a009-44fe-99a4-9cdd7404ac39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Earrings</value>
      <webElementGuid>a7c22ff5-95a5-449f-b173-aa4611416b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;affix-top&quot;]/div[@class=&quot;header-bottom&quot;]/div[@class=&quot;container clearfix pos-rel&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;site_main_menu c-buttons&quot;]/ul[@class=&quot;main-navigation&quot;]/li[@class=&quot;full-block&quot;]/a[1]</value>
      <webElementGuid>c211b712-8ffb-4420-82e0-21cd1d7b34d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>96dfafcf-623d-45dc-8484-16ee03ce0afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Earrings')]</value>
      <webElementGuid>2cc40290-f0f1-4836-b221-2518289fb6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Rings'])[1]/following::a[1]</value>
      <webElementGuid>7a3d4e5e-e190-42ea-996d-879e097ef658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silver'])[1]/following::a[2]</value>
      <webElementGuid>4f2ccea7-ec12-4381-b172-15fb03c7243b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Earring Type'])[1]/preceding::a[2]</value>
      <webElementGuid>5e31d257-6b2a-4ac1-b780-35a65a7a5342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stud'])[1]/preceding::a[2]</value>
      <webElementGuid>03cffe0a-056f-481c-8c3d-294a9dd833f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Earrings']/parent::*</value>
      <webElementGuid>1315c411-f496-47b2-b8c2-3e6294632448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jewellery/earrings.html')]</value>
      <webElementGuid>df90048d-e345-45e9-8ef5-ad0575b77e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>7636d9f1-f7f9-4585-9ace-c14dec62e4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jewellery/earrings.html' and (text() = 'Earrings' or . = 'Earrings')]</value>
      <webElementGuid>eaf0e599-c464-48b0-9573-44677109b3be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
