<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Solitaire</name>
   <tag></tag>
   <elementGuidId>1bc028ea-57f6-4044-9513-a04318a8b0db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li/ul/li[2]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dcc9c17d-3c69-46c8-abf6-ff37d0e95f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jewellery/solitaire-rings.html</value>
      <webElementGuid>cbd090a8-47b2-414d-8c5a-4a0d3af4226f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solitaire</value>
      <webElementGuid>25824e06-59a8-49c9-aeaa-d5e112f7eaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;affix-top&quot;]/div[@class=&quot;header-bottom&quot;]/div[@class=&quot;container clearfix pos-rel&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;site_main_menu c-buttons&quot;]/ul[@class=&quot;main-navigation&quot;]/li[@class=&quot;full-block&quot;]/ul[1]/li[2]/ul[1]/li[@class=&quot;no-child&quot;]/a[1]</value>
      <webElementGuid>45b755cc-f67e-496d-bc72-3fcfb6239095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>29ba0681-4bc2-4fd8-9250-1ddd9cf7d7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Solitaire')]</value>
      <webElementGuid>d0f31151-cd88-4b86-8866-9451311b74d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engagement'])[1]/following::a[1]</value>
      <webElementGuid>da149a7d-5458-4193-92a7-093eea8a9a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Wear'])[1]/following::a[2]</value>
      <webElementGuid>bd82bebd-1d68-4e02-ac34-478e23a4659f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cocktail'])[1]/preceding::a[1]</value>
      <webElementGuid>38ad3dc8-da17-4cf0-93e7-d0165537f942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office Wear'])[1]/preceding::a[2]</value>
      <webElementGuid>66404987-1f02-488b-acc2-71954231b617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solitaire']/parent::*</value>
      <webElementGuid>63010f93-d8ab-4dae-afe5-3b0872738906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jewellery/solitaire-rings.html')]</value>
      <webElementGuid>6a4ca10e-4572-46a8-8074-ed0521cb2416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>0b1a3b0e-55be-408a-b343-80ce3c94ae1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jewellery/solitaire-rings.html' and (text() = 'Solitaire' or . = 'Solitaire')]</value>
      <webElementGuid>013e9738-fee2-405b-9c18-2563f0dd97f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
