<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_The Hoprah Diamond Sui Dhaga</name>
   <tag></tag>
   <elementGuidId>685bb88d-669a-43ee-91e9-8c1fef3e5edf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[3]/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c3d094a2-c65d-49da-a55e-a4e9fd6c8e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark</value>
      <webElementGuid>fc0dc61b-fa74-41d7-ba0c-10d2bead7f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Hoprah Diamond Sui Dhaga </value>
      <webElementGuid>2c0d84a8-ce88-4f17-a104-d43a8b91212d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;clearfix&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;leftPanelOuter margin-bottom&quot;]/div[@class=&quot;light-bg sm-bg clearfix&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;productDetails col-xs-12 col-sm-6&quot;]/div[@class=&quot;light-bg inner-details&quot;]/div[@class=&quot;titleSec clearfix&quot;]/div[@class=&quot;clearfix pos-rel&quot;]/h1[@class=&quot;dark&quot;]</value>
      <webElementGuid>535cbec7-f79f-40bd-b651-2e575959ba39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/div/div/div[3]/div/div/div/h1</value>
      <webElementGuid>dfbf2641-0b4a-444e-9199-f2fd9c17bcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC Jeweller'])[1]/preceding::h1[1]</value>
      <webElementGuid>4f1c4b79-0bc7-4c08-a7d2-4d9cfb19e840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>09c298bf-b9ee-496f-94fe-e20749ffb22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'The Hoprah Diamond Sui Dhaga ' or . = 'The Hoprah Diamond Sui Dhaga ')]</value>
      <webElementGuid>edf278bf-9e73-49e5-a034-8f1014002e73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
